name: 'ClickUp GitHub Automations'
author: 'Bob VanLonkhuyzen'
description: 'A collection of GitHub Actions to automate ClickUp events'
inputs:
  task_id:
    description: The ID of the task to update in ClickUp
    required: false
  api_key:
    description: Your ClickUp API key
    required: true
branding:
  icon: 'check-circle'
  color: 'purple'
runs:
  using: 'node16'
  main: 'main.js'