name: "build-dist"
on:
  push:
    branches:
      - '*'
    paths:
      - package.json
      - package-lock.json
      - '**/*.js'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        id: extractBranch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: tool3/ncc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extractBranch.outputs.branch }}
          src: 'main.js'