name: "build-dist"
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tool3/ncc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src: 'main.js'