name: Test Action

# Controls when the action will run. Workflow runs when a commit is pushed to
# the main branch
on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: fusionary/pr-teamwork-task-tag-and-move-card@main
      with:
        task_id: 26801523
        domain: fusionary.teamwork.com
        api_key: ${{ secrets.TEAMWORK_API_KEY }}
